name: 'Create PR to other branches, on commits to a branch'
description: 'Commits, pushes a new PR branch and creates PR for the commits.'
author: '@himadrisingh'
inputs:
  pr_branch:
    description: 'Target Branch to create PR'
    required: true
  pr_labels:
    description: 'Labels for the new PR'
    required: false
    default: 'autocreated'
  pr_body:
    description: 'Description of PR'
    required: false
    default: ''
  pr_owner:
    description: 'The person who opened the PR, the person who is the author of the first commit.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: git-merge
  color: yellow
